# app/config/constants.py

SHEET_DEFAULT = "VW_CTO_FINAN"

# Colunas esperadas no export do sistema (VW_CTO_FINAN)
COLUMNS = [
    "CNPJ_EMPRESA", "TIPO", "CODIGO_INTERNO_DOCUMENTO", "CODIGO_INTERNO_TITULO",
    "NUMERO_TITULO", "PARCELA", "VALOR_TITULO", "VALOR_SALDO", "VALOR_QUITADO",
    "DATA_EMISSAO", "DATA_VENCIMENTO", "DATA_PAGAMENTO", "DATA_CREDITO",
    "SITUACAO", "SITUACAOTIPO", "NOME_PORTADOR", "FORMA_PAGAMENTO",
    "CODIGO_INTERNO_PESSOA", "CNPJ_CPF_PESSOA", "NOME_PESSOA",
    "ID_INTERNO_CONTA", "CODIGO_INTERNO_CONTA", "MASCARA_CONTA", "NOME_CONTA",
    "CODIGO_INTERNO_CENTRO_CUSTO", "NOME_CENTRO_CUSTO", "TIPO_ORIGEM",
    "TIPO_ORIGEM_DESCRICAO", "CODIGO_INTERNO_DOC_ORIGEM", "OBSERVACOES", "CTO_ATUALIZACAO"
]

REQUIRED_COLUMNS = [
    "TIPO", "VALOR_TITULO", "DATA_EMISSAO", "SITUACAO",
    "NOME_CONTA", "NOME_PESSOA", "NOME_CENTRO_CUSTO"
]